### ISSUE TITLE
chat.js

### ISSUE THREAD

**Issue by rstevens03** [flybaseio/sms-contact#1]
can't determine what is wrong but function never executes for Reply button.  Adding single line:

alert('you are here'); doesn't fire.

/message route working fine.

**Comment by freekrai** [comment]
I've updated line 94 to use `bind` instead of just `click`.

https://github.com/flybaseio/sms-contact/blob/master/public/js/chat.js#L94

This should work for you now.

**Comment by rstevens03** [comment]
Thank you.  For whatever the reason in Firefox (45.0) you get an error such
as:

The connection to wss://
push.flybase.io/socket.io/?EIO=3&transport=websocket&sid=ujys7qXO5cScwcRVAAQM
was interrupted while the page was loading. flybase.js:41:51402

I looked online, seems many people have problems like this with firefox
unrelated to flybase; Chrome has no issues at all and the sample code works
great!

Thank you,


Bob
